export const SET_ERROR_DIALOG = "SET_ERROR_DIALOG";
export const SET_SUCCESS_DIALOG = "SET_SUCCESS_DIALOG";
export const SET_STEP_SIGNUP_FORM = "SET_STEP_SIGNUP_FORM";
export const SET_SHOW_CART_MOBILE = "SET_SHOW_CART_MOBILE";
export const IS_LOADING = "IS_LOADING";
export const SET_DATA = "SET_DATA";