import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useRouter} from 'next/router'

export default function Home() {
  const router = useRouter()
  return (
    <div className={styles.container}>
      <Head>
        <title>Counter</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.title}>
            Friday Knowledge Session!
        </h2>
        <br/>

        <div className={styles.grid}>
            <button onClick={() => router.push('/drill')}>Props way &rarr;</button>
         
            <button onClick={() => router.push('/context')}>Context Hooks &rarr;</button>
            <br/>
         
            <button onClick={() => router.push('/redux')}>Redux-Thunk &rarr;</button>
            <br/>
         
            <button onClick={() => router.push('/recoil')}>Recoil.js &rarr;</button>
         

          
        </div>
      </main>

     
    </div>
  )
}
